sonar.projectKey=DaniSchreibing_Graduation
sonar.organization=danischreibing
sonar.projectVersion=1.0

# Scan both projects
sonar.sources=Flock Placement API,Python

# Test paths
sonar.tests=Flock Placement API/Tests,Python/tests

# Exclusions
sonar.exclusions=**/bin/**,**/obj/**

# Python coverage
sonar.python.coverage.reportPaths=Python/coverage.xml

# .NET test & coverage reports
sonar.cs.vstest.reportsPaths=Flock Placement API/TestResults/**/*.trx
sonar.cs.opencover.reportsPaths=Flock Placement API/TestResults/**/coverage.opencover.xml
